### ISSUE TITLE
The home button must be clicked before the search bar appears

### ISSUE THREAD

**Issue by jamescallumyoung** [ezlint/ezlint#43]
**Describe the bug**
On https://ezlint.github.io/ezlint, the home button must be clicked before the search bar appears. I believe this is due to how the router is set up and because the base path for the site on github pages includes /ezlint/ at the beginning.

**To Reproduce**
_Steps to reproduce the behavior:_
1. Go to https://ezlint.github.io/ezlint
2. Observe that the search bar is not shown
3. Click the home button (icon in the header)
4. Observe that the search bar is now shown

**Expected behavior**
The search bar should be shown correctly.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by haseeb1009** [comment]
@jamescallumyoung  I will work on this issue, can you please assign it to me?

**Comment by jamescallumyoung** [comment]
Hi @haseeb1009, thanks for the interest.

I just got a chance to see your message but it looks like @gixid192 is already working on a solution for this (they already opened a PR). I will assign it to them but feel free to check back in a few days - I will unassign it if there isn't any progress.

In the meantime, feel free to look at the other open Issues!

**Comment by jamescallumyoung** [comment]
Looks like I cannot assign it to @gixid192 since they haven't interacted with this Issue. I self-alssigned it for the meantime so others don't think ti's up for grabs.

**Comment by haseeb1009** [comment]
@jamescallumyoung  Sure
