### ISSUE TITLE
Add "fork me" / "contribute" link to homepage

### ISSUE THREAD

**Issue by jamescallumyoung** [ezlint/ezlint#44]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
We should provide a link to encourage users to contribute. The link should go to the repo on github.

**Describe alternatives you've considered**
We could just lik the repo in the footer.

**Additional context**
This was included in our original event storm.

**Comment by TheGLander** [comment]
Hello! I would like to work on this. Would using something like https://www.npmjs.com/package/fork-me-on-gh be ok?

**Comment by vabatta** [comment]
I would add the typical GitHub icon inline inside the header bar instead.

**Comment by jamescallumyoung** [comment]
Sounds good @vabatta. It might match the theme a little better.

Feel free to give this a go @TheGLander if you like. I will assign this to you so other people know you might take a look at it. If you decide no to, don't worry; I will unassign it in a few days.

**Comment by TheGLander** [comment]
Seems like that library doesn't have TS typings, @vabatta's variant should be better, then
