### ISSUE TITLE
This repo doesn't have the hacktoberfest topic set

### ISSUE THREAD

**Issue by TheGLander** [ezlint/ezlint#48]
This is more of a meta issue: The repo doesn't have the hacktoberfest topic set, thus, it doesn't count towards hacktoberfest PRs. This would be ok, except that issues here are marked with the tag, so it doesn't make sense having the hacktoberfest Issue tag while not having the hacktoberfect topic set for the repository.

**Comment by jamescallumyoung** [comment]
Hey @TheGLander, thanks for the heads up. I'm a far of hacktoberfest - even if it's caused quite a lot of spam this year - so I added the label.

**Comment by TheGLander** [comment]
Thanks, closing this
